version: '2'
services:
  job_worker:
    build: .
    tty: true
    volumes:
      - .:/job_worker
    ports:
      - 9000:9000
    command: sbt run
    depends_on:
      - mysql
      - redis
  mysql:
    # https://gist.github.com/ugdark/ec614b23a8b08c8a5a5d6a57cc4619d5
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: job_worker
    ports:
      - 3306:3306
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  # grafana
  # prometheus
