version: '2'
services:
  job_worker:
    build: .
    tty: true
    volumes:
      - .:/job_worker
    ports:
      - 9000:9000
    command: sbt run
    depends_on:
      - mysql
      - redis
  mysql:
    build:
      context: .
      dockerfile: DockerfileMysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: job_worker
    ports:
      - 3306:3306
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  # grafana
  # prometheus
