version: '2'
services:
  job_worker:
    build: .
    tty: true
    volumes:
      - .:/job_worker
    ports:
      - 9000:9000
    command: sbt run
    depends_on:
      - mysql
      - redis
  mysql:
    image: mysql:5.7
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: job_worker
    entrypoint:
      sh -c "
        echo 'CREATE DATABASE IF NOT EXISTS firstDB; CREATE DATABASE IF NOT EXISTS secondDB;' > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      "
    ports:
      - 3306:3306
  redis:
    image: redis:5.0
    ports:
      - 6379:6379
  # grafana
  # prometheus
